// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///
/// ⚠️  중요: Firebase 프로젝트 설정 필요
///
/// 이 파일은 FlutterFire CLI로 자동 생성해야 합니다:
///
/// 1. FlutterFire CLI 설치:
///    ```
///    dart pub global activate flutterfire_cli
///    ```
///
/// 2. Firebase 프로젝트 구성:
///    ```
///    flutterfire configure
///    ```
///
/// 3. 프로젝트 선택 또는 새 프로젝트 생성
///
/// 4. iOS 및 Android 플랫폼 선택
///
/// 5. 자동으로 이 파일이 올바른 설정으로 업데이트됩니다
///
/// 자세한 가이드: https://firebase.google.com/docs/flutter/setup
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCa0084HsSWRdUOYsYpbERZQYQ2dcQ6JGg',
    appId: '1:16973939404:android:99ce055820d4c7331df869',
    messagingSenderId: '16973939404',
    projectId: 'destiny-os-2026',
    storageBucket: 'destiny-os-2026.firebasestorage.app',
  );

  // ⚠️  TODO: FlutterFire CLI로 생성된 실제 값으로 교체 필요

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyNUf-sQLemTCjR_0DgMH9mVwFZkelqsM',
    appId: '1:16973939404:ios:f2ac5836a4eb8c521df869',
    messagingSenderId: '16973939404',
    projectId: 'destiny-os-2026',
    storageBucket: 'destiny-os-2026.firebasestorage.app',
    iosBundleId: 'com.destinyos.destinyOs',
  );

  // ⚠️  TODO: FlutterFire CLI로 생성된 실제 값으로 교체 필요

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBLkjvI3cEJh71UN7KaVvoiNLNy1Iih3o',
    appId: '1:16973939404:web:2cf031a507fd1a861df869',
    messagingSenderId: '16973939404',
    projectId: 'destiny-os-2026',
    authDomain: 'destiny-os-2026.firebaseapp.com',
    storageBucket: 'destiny-os-2026.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyNUf-sQLemTCjR_0DgMH9mVwFZkelqsM',
    appId: '1:16973939404:ios:f2ac5836a4eb8c521df869',
    messagingSenderId: '16973939404',
    projectId: 'destiny-os-2026',
    storageBucket: 'destiny-os-2026.firebasestorage.app',
    iosBundleId: 'com.destinyos.destinyOs',
  );

}